# Generated by Django 3.0.3 on 2020-03-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=20)),
                ('short_descriptions', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=2000)),
                ('mark_text', models.CharField(max_length=40)),
                ('mark_color', models.CharField(max_length=7)),
                ('date_published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
