# Generated by Django 3.0.3 on 2020-03-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('room', models.FloatField()),
                ('group', models.CharField(max_length=5)),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('role_user', models.CharField(choices=[('pl', 'plumber'), ('cl', 'cleaner'), ('ex', 'exterminator'), ('el', 'electrician'), ('nu', 'nurse'), ('se', 'security')], max_length=2)),
                ('created_data', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(max_length=30)),
                ('progress_user', models.CharField(choices=[('cd', 'considuration'), ('pf', 'performed'), ('rj', 'rejected'), ('rd', 'ready')], max_length=2)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
        ),
    ]
