# Generated by Django 3.0.3 on 2020-03-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200229_1405'),
        ('user', '0002_auto_20200229_2111'),
    ]

    operations = [
    ]
