# Generated by Django 3.0.3 on 2020-02-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200229_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('pl', 'plumber'), ('cl', 'cleaner'), ('ex', 'exterminator'), ('el', 'electrician'), ('nu', 'nurse'), ('se', 'security')], max_length=2)),
                ('cost', models.IntegerField()),
                ('tools', models.CharField(max_length=40)),
                ('info', models.CharField(max_length=200)),
                ('id_order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Orders')),
            ],
        ),
    ]
