# Generated by Django 3.0.3 on 2020-03-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('answer', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('pl', 'plumber'), ('cl', 'cleaner'), ('ex', 'exterminator'), ('el', 'electrician'), ('nu', 'nurse'), ('se', 'security')], max_length=2)),
                ('info', models.CharField(max_length=200)),
                ('progress', models.CharField(choices=[('cd', 'considuration'), ('pf', 'performed'), ('rj', 'rejected'), ('rd', 'ready')], max_length=2)),
                ('id_order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Orders')),
            ],
        ),
    ]
