# Generated by Django 3.0.3 on 2020-03-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='check_ans',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
