# Generated by Django 3.0.3 on 2020-02-29 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200229_2111'),
        ('order', '0002_auto_20200229_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Orders'),
        ),
    ]
