# Generated by Django 3.0.3 on 2020-03-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200229_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=100)),
                ('check_ans', models.BooleanField()),
            ],
        ),
    ]
